package intent

import (
	"fmt"
	"strings"
	"time"

	"github.com/gburgyan/aat/graph"
	"github.com/gburgyan/aat/plan"
)

// PostProcess applies deterministic fixes to a plan generated by the LLM.
// It modifies the plan in place.
func PostProcess(p *plan.Plan, g *graph.Graph, ws *WorkflowSelection, prompt string) {
	stepIndex := buildStepIndex(p)

	fixSelectionConfigs(p)
	fixDependsOn(p, g, stepIndex)
	fixFilterPrefixes(p)
	fixAssertions(p)
	addCleanupSteps(p, g)
	generateSoftConstraints(p, g)
	setMetadata(p, g, prompt)
	populateIntent(p, ws)
}

// buildStepIndex creates a set of identifiers present in the plan.
// It includes both node names (for graph edge lookups) and step IDs
// (for validating dependsOn references in composed plans where step IDs
// differ from node names, e.g., inc0_searchSeatMap vs searchSeatMap).
func buildStepIndex(p *plan.Plan) map[string]bool {
	idx := make(map[string]bool, len(p.Execution.Steps)*2)
	for _, step := range p.Execution.Steps {
		idx[step.Node] = true
		idx[step.StepID()] = true
	}
	return idx
}

// fixDependsOn ensures dependsOn reflects actual data flow and ordering
// constraints. Dependencies come from three sources:
//
//  1. Actual from references in step values and selections (data flow)
//  2. Requires/satisfies token relationships (ordering constraints)
//  3. Existing valid dependsOn entries
func fixDependsOn(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build nodeToStepIDs: maps node name → list of step IDs using that node.
	nodeToStepIDs := map[string][]string{}
	for _, step := range p.Execution.Steps {
		nodeToStepIDs[step.Node] = append(nodeToStepIDs[step.Node], step.StepID())
	}

	tokenDeps := buildTokenDeps(p, g)
	resolver := &depResolver{
		nodeToStepIDs: nodeToStepIDs,
		stepIndex:     stepIndex,
	}

	for i, step := range p.Execution.Steps {
		deps := collectStepDeps(step, g, resolver, tokenDeps)
		p.Execution.Steps[i].DependsOn = deps
	}
}

// buildTokenDeps builds requires/satisfies dependencies scoped to composition groups.
// Steps with the same prefix (e.g., "inc0_") belong to the same addon;
// steps with no prefix belong to the base workflow. A step's requires
// tokens only resolve to satisfiers within the same group to prevent
// cross-boundary cycles.
func buildTokenDeps(p *plan.Plan, g *graph.Graph) map[string][]string {
	type satisfierEntry struct {
		stepID string
		prefix string
	}
	tokenSatisfiers := map[string][]satisfierEntry{}
	stepTokenDeps := map[string][]string{}

	if g.SatisfiersByToken == nil {
		return stepTokenDeps
	}

	// Index: token → satisfier steps within each composition group.
	for _, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil {
			continue
		}
		sid := step.StepID()
		pfx := stepPrefix(sid)
		for _, token := range node.Satisfies {
			tokenSatisfiers[token] = append(tokenSatisfiers[token], satisfierEntry{sid, pfx})
		}
	}
	// For each step that requires a token, find same-prefix satisfiers.
	for _, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil {
			continue
		}
		sid := step.StepID()
		pfx := stepPrefix(sid)
		for _, token := range node.Requires {
			for _, sat := range tokenSatisfiers[token] {
				if sat.prefix == pfx && sat.stepID != sid {
					stepTokenDeps[sid] = append(stepTokenDeps[sid], sat.stepID)
				}
			}
		}
	}
	return stepTokenDeps
}

// depResolver resolves dependency references to actual step IDs, preferring
// same-group matches for composed plans.
type depResolver struct {
	nodeToStepIDs map[string][]string
	stepIndex     map[string]bool
}

// resolve adds the resolved dependency step IDs to the required set. If dep is
// a node name, it maps to step IDs using that node. If dep is already a step
// ID, it's added directly. Prefers same-group matches to avoid cross-boundary
// dependencies.
func (dr *depResolver) resolve(required map[string]bool, dep, selfStepID string) {
	if sids, ok := dr.nodeToStepIDs[dep]; ok {
		selfPfx := stepPrefix(selfStepID)
		var sameGroup []string
		for _, sid := range sids {
			if sid != selfStepID && stepPrefix(sid) == selfPfx {
				sameGroup = append(sameGroup, sid)
			}
		}
		if len(sameGroup) > 0 {
			for _, sid := range sameGroup {
				required[sid] = true
			}
			return
		}
		// No same-group match: use all (cross-boundary ref).
		for _, sid := range sids {
			if sid != selfStepID {
				required[sid] = true
			}
		}
		return
	}
	// dep is already a step ID (not a node name).
	if dr.stepIndex[dep] && dep != selfStepID {
		required[dep] = true
	}
}

// collectStepDeps collects all dependencies for a single step from from-refs,
// selections, graph defaults, token deps, and existing dependsOn.
func collectStepDeps(step plan.Step, g *graph.Graph, resolver *depResolver, tokenDeps map[string][]string) []string {
	stepID := step.StepID()
	required := map[string]bool{}

	// 1. Dependencies from actual from references in values.
	for _, sv := range step.Values {
		if sv.From != "" {
			resolver.resolve(required, splitNodeName(sv.From), stepID)
		}
	}

	// 2. Dependencies from actual from references in named selections.
	for _, sel := range step.Selections {
		if sel.From != "" {
			resolver.resolve(required, splitNodeName(sel.From), stepID)
		}
	}

	// 2b. Dependencies from graph-level default from references.
	node := g.Nodes[step.Node]
	if node != nil {
		for _, inp := range node.Inputs {
			if _, hasPlanValue := step.Values[inp.Name]; hasPlanValue {
				continue
			}
			if inp.Default != nil && inp.Default.From != "" {
				resolver.resolve(required, splitNodeName(inp.Default.From), stepID)
			}
		}
	}

	// 3. Requires/satisfies token deps (ordering constraints, scoped to composition group).
	for _, depStepID := range tokenDeps[stepID] {
		required[depStepID] = true
	}

	// 4. Existing valid dependsOn entries (resolved via resolver
	// so bare node names get mapped to prefixed step IDs).
	for _, dep := range step.DependsOn {
		resolver.resolve(required, dep, stepID)
	}

	// Build sorted list.
	deps := make([]string, 0, len(required))
	for dep := range required {
		deps = append(deps, dep)
	}
	sortStrings(deps)
	return deps
}

// fixSelectionConfigs ensures named selections have a strategy set.
// Defaults empty strategy to "first".
func fixSelectionConfigs(p *plan.Plan) {
	for i, step := range p.Execution.Steps {
		if p.Execution.Steps[i].Values == nil {
			p.Execution.Steps[i].Values = map[string]plan.StepValue{}
		}

		// Fix named selection strategies: default empty strategy to "first"
		for selName, sel := range step.Selections {
			if sel.Strategy == "" {
				sel.Strategy = "first"
				p.Execution.Steps[i].Selections[selName] = sel
			}
		}

		// Fix inline selection strategies: default empty strategy to "first"
		for name, sv := range step.Values {
			if sv.Select != nil && sv.Select.Strategy == "" {
				sv.Select.Strategy = "first"
				p.Execution.Steps[i].Values[name] = sv
			}
		}
	}
}

// fixFilterPrefixes strips selection-name prefixes from filter expressions.
// LLMs sometimes generate filters like "catalogProductOffering.carrier == 'QF'"
// when the correct form is "carrier == 'QF'" (field names are relative to the
// selected element, not qualified by selection name).
func fixFilterPrefixes(p *plan.Plan) {
	for i, step := range p.Execution.Steps {
		for selName, sel := range step.Selections {
			if sel.Filter == "" {
				continue
			}
			prefix := selName + "."
			if strings.Contains(sel.Filter, prefix) {
				sel.Filter = strings.ReplaceAll(sel.Filter, prefix, "")
				p.Execution.Steps[i].Selections[selName] = sel
			}
		}
		for name, sv := range step.Values {
			if sv.Select != nil && sv.Select.Filter != "" {
				// For inline selections, the "selection name" is the value name
				prefix := name + "."
				if strings.Contains(sv.Select.Filter, prefix) {
					sv.Select.Filter = strings.ReplaceAll(sv.Select.Filter, prefix, "")
					p.Execution.Steps[i].Values[name] = sv
				}
			}
		}
	}
}

// validAssertionTypes is the set of recognized mechanical assertion types.
var validAssertionTypes = map[string]bool{
	"status":      true,
	"schema":      true,
	"fieldExists": true,
	"fieldEquals": true,
	"predicate":   true,
}

// fixAssertions removes mechanical assertions with empty or unknown types and
// ensures every step has at least a status assertion. LLMs sometimes produce
// assertions with missing type fields; this cleans them up.
//
// For expectFailure steps, the default status assertion uses the first expected
// failure code instead of 200 (which would contradict the expected failure).
func fixAssertions(p *plan.Plan) {
	for i := range p.Execution.Steps {
		step := &p.Execution.Steps[i]
		if step.Assertions == nil {
			step.Assertions = &plan.Assertions{}
		}

		// Filter to valid assertions only.
		var valid []plan.MechanicalAssertion
		hasStatus := false
		for _, a := range step.Assertions.Mechanical {
			if !validAssertionTypes[a.Type] {
				continue
			}
			if a.Type == "status" {
				hasStatus = true
			}
			valid = append(valid, a)
		}

		// Ensure at least a status assertion.
		if !hasStatus {
			defaultStatus := 200
			if step.ExpectFailure != nil && len(step.ExpectFailure.Status) > 0 {
				defaultStatus = step.ExpectFailure.Status[0]
			}
			valid = append([]plan.MechanicalAssertion{{
				Type:   "status",
				Expect: defaultStatus,
			}}, valid...)
		}

		step.Assertions.Mechanical = valid
	}
}

// addCleanupSteps ensures cleanup steps exist for nodes that have Cleanup fields.
func addCleanupSteps(p *plan.Plan, g *graph.Graph) {
	// Build set of existing cleanup nodes
	existingCleanup := map[string]bool{}
	for _, cs := range p.Execution.Cleanup {
		existingCleanup[cs.Node] = true
	}

	for _, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil || node.Cleanup == "" {
			continue
		}

		if !existingCleanup[node.Cleanup] {
			p.Execution.Cleanup = append(p.Execution.Cleanup, plan.CleanupStep{
				Node:  node.Cleanup,
				RunOn: "always",
			})
			existingCleanup[node.Cleanup] = true
		}
	}
}

// setMetadata populates plan metadata fields.
func setMetadata(p *plan.Plan, g *graph.Graph, prompt string) {
	setMetadataWithTime(p, g, prompt, time.Now())
}

// generateSoftConstraints creates soft constraints from LLM-provided selection
// overrides (filters and sort fields). The engine's relaxation system uses these
// to know what can be relaxed when a selection produces no results.
//
// Any selection filter or sort field that was set (either by the LLM or from the
// template) generates a soft constraint with AppliesTo pointing to the step.
// This is deterministic — no LLM involvement.
func generateSoftConstraints(p *plan.Plan, g *graph.Graph) {
	var softConstraints []plan.Constraint

	for _, step := range p.Execution.Steps {
		stepID := step.StepID()

		// Named selections.
		for selName, sel := range step.Selections {
			if sel.Filter != "" {
				name := deriveSoftConstraintName(selName, sel.Filter)
				softConstraints = append(softConstraints, plan.Constraint{
					Name:        name,
					Description: fmt.Sprintf("selection filter: %s", sel.Filter),
					AppliesTo:   []string{stepID},
				})
			}
			if sel.SortField != "" && (sel.Strategy == "min" || sel.Strategy == "max") {
				name := sel.Strategy + " " + sel.SortField + " preference"
				softConstraints = append(softConstraints, plan.Constraint{
					Name:        name,
					Description: fmt.Sprintf("selection sort: %s %s", sel.Strategy, sel.SortField),
					AppliesTo:   []string{stepID},
				})
			}
		}

		// Inline selections (from+select on values).
		for _, sv := range step.Values {
			if sv.Select == nil {
				continue
			}
			if sv.Select.Filter != "" {
				name := deriveSoftConstraintName("selection", sv.Select.Filter)
				softConstraints = append(softConstraints, plan.Constraint{
					Name:        name,
					Description: fmt.Sprintf("selection filter: %s", sv.Select.Filter),
					AppliesTo:   []string{stepID},
				})
			}
			if sv.Select.SortField != "" && (sv.Select.Strategy == "min" || sv.Select.Strategy == "max") {
				name := sv.Select.Strategy + " " + sv.Select.SortField + " preference"
				softConstraints = append(softConstraints, plan.Constraint{
					Name:        name,
					Description: fmt.Sprintf("selection sort: %s %s", sv.Select.Strategy, sv.Select.SortField),
					AppliesTo:   []string{stepID},
				})
			}
		}
	}

	if len(softConstraints) == 0 {
		return
	}

	if p.Intent.Constraints == nil {
		p.Intent.Constraints = &plan.Constraints{}
	}
	p.Intent.Constraints.Soft = append(p.Intent.Constraints.Soft, softConstraints...)
}

// deriveSoftConstraintName creates a human-readable name from a filter expression.
func deriveSoftConstraintName(context, filter string) string {
	// Common patterns: "maxConnections == 0" → "nonstop preference"
	lower := strings.ToLower(filter)
	if strings.Contains(lower, "connection") && strings.Contains(lower, "0") {
		return "nonstop preference"
	}
	if strings.Contains(lower, "carrier") {
		return "carrier preference"
	}
	return context + " filter preference"
}

// populateIntent sets the plan description from the workflow selection.
func populateIntent(p *plan.Plan, ws *WorkflowSelection) {
	if ws == nil {
		return
	}

	if p.Intent.Description == "" {
		p.Intent.Description = ws.Description
	}
}

// MergeLLMValues merges LLM-provided creative content into the skeleton plan,
// matching steps by node name. The skeleton's structural fields are authoritative;
// the LLM only adds/overrides values, descriptions, assertions, selection strategy
// refinements, and retry config.
//
// The unfed parameter gates which new inputs (not already in the skeleton) are
// accepted; see MergeLLMValuesWithIDs for details. If unfed is nil, all
// LLM-provided new values are accepted (legacy behavior).
func MergeLLMValues(skeleton, llmPlan *plan.Plan, unfed map[string]bool) {
	// Build index of LLM steps by node name.
	llmSteps := map[string]*plan.Step{}
	for i := range llmPlan.Execution.Steps {
		llmSteps[llmPlan.Execution.Steps[i].Node] = &llmPlan.Execution.Steps[i]
	}

	for i := range skeleton.Execution.Steps {
		skelStep := &skeleton.Execution.Steps[i]
		llmStep, ok := llmSteps[skelStep.Node]
		if !ok {
			continue
		}
		mergeStepFromLLM(skelStep, llmStep, unfed)
	}
}

// mergeStepFromLLM merges LLM-provided creative content into a single skeleton
// step. The skeleton's structural fields are authoritative; the LLM only
// adds/overrides values, descriptions, assertions, selection strategy
// refinements, and retry config. unfed gates which new inputs are accepted.
func mergeStepFromLLM(skelStep *plan.Step, llmStep *plan.Step, unfed map[string]bool) {
	// Accept description from LLM.
	if llmStep.Description != "" {
		skelStep.Description = llmStep.Description
	}

	// Accept assertions from LLM.
	if llmStep.Assertions != nil {
		skelStep.Assertions = llmStep.Assertions
	}

	// Accept retry config from LLM.
	if llmStep.Retry != nil {
		skelStep.Retry = llmStep.Retry
	}

	// Merge named selection strategy overrides from LLM.
	if len(skelStep.Selections) > 0 && len(llmStep.Selections) > 0 {
		for selName, llmSel := range llmStep.Selections {
			skelSel, exists := skelStep.Selections[selName]
			if !exists {
				continue // ignore selections the skeleton doesn't have
			}
			if llmSel.Strategy != "" {
				skelSel.Strategy = llmSel.Strategy
			}
			if llmSel.Filter != "" {
				skelSel.Filter = llmSel.Filter
			}
			if llmSel.SortField != "" {
				skelSel.SortField = llmSel.SortField
			}
			if llmSel.Prompt != "" {
				skelSel.Prompt = llmSel.Prompt
			}
			if llmSel.Index != 0 {
				skelSel.Index = llmSel.Index
			}
			skelStep.Selections[selName] = skelSel
		}
	}

	// Merge values.
	if llmStep.Values == nil {
		return
	}
	if skelStep.Values == nil {
		skelStep.Values = map[string]plan.StepValue{}
	}

	for inputName, llmVal := range llmStep.Values {
		skelVal, exists := skelStep.Values[inputName]

		if !exists {
			// Only accept new literals for inputs that genuinely need values.
			key := skelStep.StepID() + "." + inputName
			if llmVal.Default != nil && (unfed == nil || unfed[key]) {
				skelStep.Values[inputName] = plan.StepValue{
					Default: llmVal.Default,
				}
			}
			continue
		}

		// Skeleton has an entry. Merge based on what skeleton has.
		if skelVal.FromSelection != "" {
			// Named selection: skeleton is authoritative. Skip.
			continue
		} else if skelVal.From != "" && skelVal.Select != nil {
			// Select edge: accept strategy/filter/sortField/index/prompt overrides.
			if llmVal.Select != nil {
				if llmVal.Select.Strategy != "" {
					skelVal.Select.Strategy = llmVal.Select.Strategy
				}
				if llmVal.Select.Filter != "" {
					skelVal.Select.Filter = llmVal.Select.Filter
				}
				if llmVal.Select.SortField != "" {
					skelVal.Select.SortField = llmVal.Select.SortField
				}
				if llmVal.Select.Index != 0 {
					skelVal.Select.Index = llmVal.Select.Index
				}
				if llmVal.Select.Prompt != "" {
					skelVal.Select.Prompt = llmVal.Select.Prompt
				}
			}
			skelStep.Values[inputName] = skelVal
		} else if skelVal.From != "" {
			// Scalar from ref: skeleton is authoritative.
		} else {
			// Graph default or empty: accept LLM literal override.
			if llmVal.Default != nil {
				skelVal.Default = llmVal.Default
			}
			skelStep.Values[inputName] = skelVal
		}
	}
}

// setMetadataWithTime populates plan metadata with a specific time.
func setMetadataWithTime(p *plan.Plan, g *graph.Graph, prompt string, now time.Time) {
	p.Metadata.Prompt = prompt
	p.Metadata.GraphVersion = g.Version
	if p.Metadata.Created.IsZero() {
		p.Metadata.Created = now
	}
}

// lookupElementFieldPath finds the elementField name for an input fed by a
// select edge. It returns the elementField Name (not the gjson path) so that
// plans remain decoupled from response structure. The engine resolves the
// name to a gjson path at runtime via resolveElementFieldPath.
// Falls back to inputName if no matching elementField exists.
func lookupElementFieldPath(g *graph.Graph, sourceRef, inputName string) string {
	srcNode := splitNodeName(sourceRef)
	srcField := sourceRef[len(srcNode)+1:]
	node := g.Nodes[srcNode]
	if node == nil {
		return inputName
	}
	for _, out := range node.Outputs {
		if out.Name == srcField {
			for _, ef := range out.ElementFields {
				if ef.Name == inputName {
					return ef.Name
				}
			}
			break
		}
	}
	return inputName
}

// deriveSelectionName creates a name for a named selection from the source
// reference. It takes the last segment (e.g., "catalogOfferings" from
// "searchFlights.catalogOfferings") and makes it singular-ish.
func deriveSelectionName(source string) string {
	parts := strings.SplitN(source, ".", 2)
	if len(parts) < 2 {
		return "selection"
	}
	name := parts[1]
	// Simple singularization: strip trailing 's' if it exists
	if len(name) > 1 && name[len(name)-1] == 's' {
		name = name[:len(name)-1]
	}
	return name
}

// stepPrefix extracts the composition-group prefix from a step ID.
// Addon steps have prefixes like "inc0_", "inc1_", etc.
// Base workflow steps have no prefix (returns "").
func stepPrefix(stepID string) string {
	if strings.HasPrefix(stepID, "inc") {
		if idx := strings.Index(stepID, "_"); idx >= 0 {
			return stepID[:idx+1]
		}
	}
	return ""
}

// splitNodeName extracts the node name from a "node.field" reference.
func splitNodeName(ref string) string {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

// blankBrokenFromSelections scans the plan for fromSelection values whose
// field component is not a valid elementField on the source output. Any such
// values have their FromSelection cleared (making them unfed inputs for the
// LLM retry). Returns the list of blanked "step.input" keys and a description
// of what the correct elementFields are for the retry prompt.
func blankBrokenFromSelections(p *plan.Plan, g *graph.Graph) (blanked []string, hints []string) {
	outputsByNode := make(map[string]map[string]graph.Output)
	for name, node := range g.Nodes {
		outs := make(map[string]graph.Output, len(node.Outputs))
		for _, out := range node.Outputs {
			outs[out.Name] = out
		}
		outputsByNode[name] = outs
	}

	for i, step := range p.Execution.Steps {
		for inputName, sv := range step.Values {
			if sv.FromSelection == "" {
				continue
			}
			selName, fieldName := plan.ParseFromSelection(sv.FromSelection)
			if fieldName == "" {
				continue
			}
			sel, selExists := step.Selections[selName]
			if !selExists || sel.From == "" {
				continue
			}
			parts := strings.SplitN(sel.From, ".", 2)
			if len(parts) != 2 {
				continue
			}
			srcNode, srcField := parts[0], parts[1]
			outs, ok := outputsByNode[srcNode]
			if !ok {
				continue
			}
			out, outExists := outs[srcField]
			if !outExists || len(out.ElementFields) == 0 {
				continue
			}
			found := false
			for _, ef := range out.ElementFields {
				if ef.Name == fieldName {
					found = true
					break
				}
			}
			if !found {
				blanked = append(blanked, step.Node+"."+inputName)
				sv.FromSelection = ""
				p.Execution.Steps[i].Values[inputName] = sv

				// Build hint showing available elementFields
				var efNames []string
				for _, ef := range out.ElementFields {
					efNames = append(efNames, ef.Name)
				}
				hints = append(hints, fmt.Sprintf(
					"Available elementFields for %s.%s: %s",
					srcNode, srcField, strings.Join(efNames, ", ")))
			}
		}
	}
	return blanked, hints
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		key := s[i]
		j := i - 1
		for j >= 0 && s[j] > key {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = key
	}
}
