package intent

import (
	"strings"
	"time"

	"github.com/gburgyan/aat/graph"
	"github.com/gburgyan/aat/plan"
)

// PostProcess applies deterministic fixes to a plan generated by the LLM.
// It modifies the plan in place.
func PostProcess(p *plan.Plan, g *graph.Graph, cr *graph.ChainResult, ga *GoalAnalysis, prompt string) {
	stepIndex := buildStepIndex(p)

	fixDependsOn(p, g, stepIndex)
	fixSelectionConfigs(p, g, stepIndex)
	addCleanupSteps(p, g, stepIndex)
	setMetadata(p, g, ga, prompt)
	populateIntent(p, ga)
}

// buildStepIndex creates a set of node names present in the plan.
func buildStepIndex(p *plan.Plan) map[string]bool {
	idx := make(map[string]bool, len(p.Execution.Steps))
	for _, step := range p.Execution.Steps {
		idx[step.Node] = true
	}
	return idx
}

// fixDependsOn ensures dependsOn reflects actual graph edge dependencies.
// For each step, if a source node (from graph edges) is in the plan, it
// must be in dependsOn. Invalid dependsOn entries are removed.
func fixDependsOn(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build edge-based dependencies: targetNode → set of sourceNodes
	edgeDeps := map[string]map[string]bool{}
	for _, edge := range g.Edges {
		fromNode := splitNodeName(edge.From)
		toNode := splitNodeName(edge.To)
		if fromNode == "" || toNode == "" {
			continue
		}
		if edgeDeps[toNode] == nil {
			edgeDeps[toNode] = map[string]bool{}
		}
		edgeDeps[toNode][fromNode] = true
	}

	for i, step := range p.Execution.Steps {
		required := map[string]bool{}

		// Add dependencies from graph edges
		for dep := range edgeDeps[step.Node] {
			if stepIndex[dep] && dep != step.Node {
				required[dep] = true
			}
		}

		// Add existing valid dependsOn entries
		for _, dep := range step.DependsOn {
			if stepIndex[dep] && dep != step.Node {
				required[dep] = true
			}
		}

		// Build sorted list
		deps := make([]string, 0, len(required))
		for dep := range required {
			deps = append(deps, dep)
		}
		sortStrings(deps)

		p.Execution.Steps[i].DependsOn = deps
	}
}

// fixSelectionConfigs ensures that inputs fed by select edges have proper
// from/select config. If missing, defaults to strategy: first.
func fixSelectionConfigs(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build select edge index: "toNode.toInput" → "fromNode.fromOutput"
	selectEdges := map[string]string{}
	for _, edge := range g.Edges {
		if edge.Select {
			selectEdges[edge.To] = edge.From
		}
	}

	for i, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil {
			continue
		}

		if p.Execution.Steps[i].Values == nil {
			p.Execution.Steps[i].Values = map[string]plan.StepValue{}
		}

		for _, inp := range node.Inputs {
			edgeKey := step.Node + "." + inp.Name
			source, isSelect := selectEdges[edgeKey]
			if !isSelect {
				continue
			}

			// Check if source node is in the plan
			sourceNode := splitNodeName(source)
			if !stepIndex[sourceNode] {
				continue
			}

			sv, exists := step.Values[inp.Name]
			if !exists {
				sv = plan.StepValue{}
			}

			// Ensure from is set
			if sv.From == "" {
				sv.From = source
			}

			// Ensure select config exists with a default strategy
			if sv.Select == nil {
				sv.Select = &plan.SelectionConfig{
					Strategy: "first",
					Field:    inp.Name,
				}
			} else if sv.Select.Strategy == "" {
				sv.Select.Strategy = "first"
			}

			p.Execution.Steps[i].Values[inp.Name] = sv
		}
	}
}

// addCleanupSteps ensures cleanup steps exist for nodes that have Cleanup fields.
func addCleanupSteps(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build set of existing cleanup nodes
	existingCleanup := map[string]bool{}
	for _, cs := range p.Execution.Cleanup {
		existingCleanup[cs.Node] = true
	}

	for _, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil || node.Cleanup == "" {
			continue
		}

		if !existingCleanup[node.Cleanup] {
			p.Execution.Cleanup = append(p.Execution.Cleanup, plan.CleanupStep{
				Node:  node.Cleanup,
				RunOn: "always",
			})
			existingCleanup[node.Cleanup] = true
		}
	}
}

// setMetadata populates plan metadata fields.
func setMetadata(p *plan.Plan, g *graph.Graph, ga *GoalAnalysis, prompt string) {
	p.Metadata.Prompt = prompt
	p.Metadata.GraphVersion = g.Version
	if p.Metadata.Created.IsZero() {
		p.Metadata.Created = time.Now()
	}
}

// populateIntent transfers constraint classification from GoalAnalysis into the plan.
func populateIntent(p *plan.Plan, ga *GoalAnalysis) {
	if ga == nil {
		return
	}

	p.Intent.Goal = ga.Goal
	if p.Intent.Description == "" {
		p.Intent.Description = ga.Description
	}

	if len(ga.Constraints.Hard) > 0 || len(ga.Constraints.Soft) > 0 || len(ga.Constraints.Free) > 0 {
		if p.Intent.Constraints == nil {
			p.Intent.Constraints = &plan.Constraints{}
		}
		for _, h := range ga.Constraints.Hard {
			p.Intent.Constraints.Hard = append(p.Intent.Constraints.Hard, plan.Constraint{
				Name:        h.Name,
				Description: h.Description,
				AppliesTo:   h.AppliesTo,
			})
		}
		for _, s := range ga.Constraints.Soft {
			p.Intent.Constraints.Soft = append(p.Intent.Constraints.Soft, plan.Constraint{
				Name:        s.Name,
				Description: s.Description,
				AppliesTo:   s.AppliesTo,
			})
		}
		p.Intent.Constraints.Free = append(p.Intent.Constraints.Free, ga.Constraints.Free...)
	}
}

// splitNodeName extracts the node name from a "node.field" reference.
func splitNodeName(ref string) string {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		key := s[i]
		j := i - 1
		for j >= 0 && s[j] > key {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = key
	}
}
