package intent

import (
	"fmt"
	"strings"
	"time"

	"github.com/gburgyan/aat/graph"
	"github.com/gburgyan/aat/plan"
)

// PostProcess applies deterministic fixes to a plan generated by the LLM.
// It modifies the plan in place.
func PostProcess(p *plan.Plan, g *graph.Graph, cr *graph.ChainResult, ga *GoalAnalysis, prompt string) {
	stepIndex := buildStepIndex(p)

	fixDependsOn(p, g, stepIndex)
	fixSelectionConfigs(p, g, stepIndex)
	fixAssertions(p)
	addCleanupSteps(p, g, stepIndex)
	setMetadata(p, g, ga, prompt)
	populateIntent(p, ga)
}

// buildStepIndex creates a set of node names present in the plan.
func buildStepIndex(p *plan.Plan) map[string]bool {
	idx := make(map[string]bool, len(p.Execution.Steps))
	for _, step := range p.Execution.Steps {
		idx[step.Node] = true
	}
	return idx
}

// fixDependsOn ensures dependsOn reflects actual graph edge dependencies.
// For each step, if a source node (from graph edges) is in the plan, it
// must be in dependsOn. Invalid dependsOn entries are removed.
func fixDependsOn(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build edge-based dependencies: targetNode → set of sourceNodes
	edgeDeps := map[string]map[string]bool{}
	for _, edge := range g.Edges {
		fromNode := splitNodeName(edge.From)
		toNode := splitNodeName(edge.To)
		if fromNode == "" || toNode == "" {
			continue
		}
		if edgeDeps[toNode] == nil {
			edgeDeps[toNode] = map[string]bool{}
		}
		edgeDeps[toNode][fromNode] = true
	}

	for i, step := range p.Execution.Steps {
		required := map[string]bool{}

		// Add dependencies from graph edges
		for dep := range edgeDeps[step.Node] {
			if stepIndex[dep] && dep != step.Node {
				required[dep] = true
			}
		}

		// Add existing valid dependsOn entries
		for _, dep := range step.DependsOn {
			if stepIndex[dep] && dep != step.Node {
				required[dep] = true
			}
		}

		// Build sorted list
		deps := make([]string, 0, len(required))
		for dep := range required {
			deps = append(deps, dep)
		}
		sortStrings(deps)

		p.Execution.Steps[i].DependsOn = deps
	}
}

// fixSelectionConfigs ensures that inputs fed by select edges have proper
// from/select config. If missing, defaults to strategy: first.
func fixSelectionConfigs(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build select edge index: "toNode.toInput" → "fromNode.fromOutput"
	selectEdges := map[string]string{}
	for _, edge := range g.Edges {
		if edge.Select {
			selectEdges[edge.To] = edge.From
		}
	}

	for i, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil {
			continue
		}

		if p.Execution.Steps[i].Values == nil {
			p.Execution.Steps[i].Values = map[string]plan.StepValue{}
		}

		for _, inp := range node.Inputs {
			edgeKey := step.Node + "." + inp.Name
			source, isSelect := selectEdges[edgeKey]
			if !isSelect {
				continue
			}

			// Check if source node is in the plan
			sourceNode := splitNodeName(source)
			if !stepIndex[sourceNode] {
				continue
			}

			sv, exists := step.Values[inp.Name]
			if !exists {
				sv = plan.StepValue{}
			}

			// Ensure from is set
			if sv.From == "" {
				sv.From = source
			}

			// Ensure select config exists with a default strategy
			if sv.Select == nil {
				sv.Select = &plan.SelectionConfig{
					Strategy: "first",
					Field:    lookupElementFieldPath(g, source, inp.Name),
				}
			} else if sv.Select.Strategy == "" {
				sv.Select.Strategy = "first"
			}

			p.Execution.Steps[i].Values[inp.Name] = sv
		}
	}
}

// validAssertionTypes is the set of recognized mechanical assertion types.
var validAssertionTypes = map[string]bool{
	"status":      true,
	"schema":      true,
	"fieldExists": true,
	"fieldEquals": true,
	"predicate":   true,
}

// fixAssertions removes mechanical assertions with empty or unknown types and
// ensures every step has at least a status assertion. LLMs sometimes produce
// assertions with missing type fields; this cleans them up.
func fixAssertions(p *plan.Plan) {
	for i := range p.Execution.Steps {
		step := &p.Execution.Steps[i]
		if step.Assertions == nil {
			step.Assertions = &plan.Assertions{}
		}

		// Filter to valid assertions only.
		var valid []plan.MechanicalAssertion
		hasStatus := false
		for _, a := range step.Assertions.Mechanical {
			if !validAssertionTypes[a.Type] {
				continue
			}
			if a.Type == "status" {
				hasStatus = true
			}
			valid = append(valid, a)
		}

		// Ensure at least a status 200 assertion.
		if !hasStatus {
			valid = append([]plan.MechanicalAssertion{{
				Type:   "status",
				Expect: 200,
			}}, valid...)
		}

		step.Assertions.Mechanical = valid
	}
}

// addCleanupSteps ensures cleanup steps exist for nodes that have Cleanup fields.
func addCleanupSteps(p *plan.Plan, g *graph.Graph, stepIndex map[string]bool) {
	// Build set of existing cleanup nodes
	existingCleanup := map[string]bool{}
	for _, cs := range p.Execution.Cleanup {
		existingCleanup[cs.Node] = true
	}

	for _, step := range p.Execution.Steps {
		node := g.Nodes[step.Node]
		if node == nil || node.Cleanup == "" {
			continue
		}

		if !existingCleanup[node.Cleanup] {
			p.Execution.Cleanup = append(p.Execution.Cleanup, plan.CleanupStep{
				Node:  node.Cleanup,
				RunOn: "always",
			})
			existingCleanup[node.Cleanup] = true
		}
	}
}

// setMetadata populates plan metadata fields.
func setMetadata(p *plan.Plan, g *graph.Graph, ga *GoalAnalysis, prompt string) {
	setMetadataWithTime(p, g, ga, prompt, time.Now())
}

// populateIntent transfers constraint classification from GoalAnalysis into the plan.
func populateIntent(p *plan.Plan, ga *GoalAnalysis) {
	if ga == nil {
		return
	}

	p.Intent.Goal = ga.Goal
	if p.Intent.Description == "" {
		p.Intent.Description = ga.Description
	}

	// Only backfill constraints from GoalAnalysis if the LLM didn't already
	// populate them in the YAML. This prevents duplication when the LLM
	// includes constraints (it has full visibility of GoalAnalysis in the prompt).
	if p.Intent.Constraints == nil {
		if len(ga.Constraints.Hard) > 0 || len(ga.Constraints.Soft) > 0 || len(ga.Constraints.Free) > 0 {
			p.Intent.Constraints = &plan.Constraints{}
			for _, h := range ga.Constraints.Hard {
				p.Intent.Constraints.Hard = append(p.Intent.Constraints.Hard, plan.Constraint{
					Name:        h.Name,
					Description: h.Description,
					AppliesTo:   h.AppliesTo,
				})
			}
			for _, s := range ga.Constraints.Soft {
				p.Intent.Constraints.Soft = append(p.Intent.Constraints.Soft, plan.Constraint{
					Name:        s.Name,
					Description: s.Description,
					AppliesTo:   s.AppliesTo,
				})
			}
			p.Intent.Constraints.Free = append(p.Intent.Constraints.Free, ga.Constraints.Free...)
		}
	}
}

// BuildSkeleton constructs a deterministic plan scaffold from the graph,
// backward chain result, and goal analysis. All structural elements (steps,
// dependsOn, from refs, select configs, cleanup, metadata, intent) are
// computed from the graph. Only literal values for unfed inputs are left
// empty for the LLM to fill.
func BuildSkeleton(g *graph.Graph, cr *graph.ChainResult, ga *GoalAnalysis, prompt string, now time.Time) *plan.Plan {
	p := &plan.Plan{}

	// Build edge indexes from the chain's edges (not the full graph).
	// allEdges: "toNode.toInput" → "fromNode.fromOutput"
	allEdges := map[string]string{}
	// selectEdges: same but only for select:true edges
	selectEdges := map[string]string{}
	for _, edge := range cr.Edges {
		allEdges[edge.To] = edge.From
		if edge.Select {
			selectEdges[edge.To] = edge.From
		}
	}

	// Build step index from chain nodes.
	stepIndex := map[string]bool{}
	for _, name := range cr.Nodes {
		stepIndex[name] = true
	}

	// Build edge-based dependency map: targetNode → set of sourceNodes
	edgeDeps := map[string]map[string]bool{}
	for _, edge := range cr.Edges {
		fromNode := splitNodeName(edge.From)
		toNode := splitNodeName(edge.To)
		if fromNode == "" || toNode == "" {
			continue
		}
		if edgeDeps[toNode] == nil {
			edgeDeps[toNode] = map[string]bool{}
		}
		edgeDeps[toNode][fromNode] = true
	}

	// Create steps in chain order.
	for _, nodeName := range cr.Nodes {
		node := g.Nodes[nodeName]
		if node == nil {
			continue
		}

		step := plan.Step{
			Node:   nodeName,
			IsGoal: ga != nil && nodeName == ga.Goal,
			Values: map[string]plan.StepValue{},
		}

		// Compute dependsOn from chain edges.
		deps := map[string]bool{}
		for dep := range edgeDeps[nodeName] {
			if stepIndex[dep] && dep != nodeName {
				deps[dep] = true
			}
		}
		depList := make([]string, 0, len(deps))
		for dep := range deps {
			depList = append(depList, dep)
		}
		sortStrings(depList)
		step.DependsOn = depList

		// For each input, wire up from/select or leave empty for LLM.
		for _, inp := range node.Inputs {
			edgeKey := nodeName + "." + inp.Name

			if source, isSelect := selectEdges[edgeKey]; isSelect {
				// Select edge: set from + select config.
				sourceNode := splitNodeName(source)
				if stepIndex[sourceNode] {
					step.Values[inp.Name] = plan.StepValue{
						From: source,
						Select: &plan.SelectionConfig{
							Strategy: "first",
							Field:    lookupElementFieldPath(g, source, inp.Name),
						},
					}
				}
			} else if source, hasEdge := allEdges[edgeKey]; hasEdge {
				// Scalar edge: set from only.
				sourceNode := splitNodeName(source)
				if stepIndex[sourceNode] {
					step.Values[inp.Name] = plan.StepValue{
						From: source,
					}
				}
			} else if inp.Default != nil {
				// Graph-level default: set as default value.
				step.Values[inp.Name] = plan.StepValue{
					Default: inp.Default,
				}
			}
			// else: unfed input → leave absent, LLM will fill it.
		}

		p.Execution.Steps = append(p.Execution.Steps, step)
	}

	// Add cleanup steps.
	addCleanupSteps(p, g, stepIndex)

	// Set metadata and intent.
	setMetadataWithTime(p, g, ga, prompt, now)
	populateIntent(p, ga)

	return p
}

// UnfedInputs returns a list of "node.input" keys that have no edge feeding
// them and no graph-level default — these need LLM-provided values.
func UnfedInputs(g *graph.Graph, cr *graph.ChainResult) []string {
	// Build fed set from chain edges.
	fed := map[string]bool{}
	for _, edge := range cr.Edges {
		fed[edge.To] = true
	}

	var unfed []string
	for _, nodeName := range cr.Nodes {
		node := g.Nodes[nodeName]
		if node == nil {
			continue
		}
		for _, inp := range node.Inputs {
			key := nodeName + "." + inp.Name
			if fed[key] {
				continue
			}
			if inp.Optional {
				continue
			}
			if inp.Default != nil {
				continue
			}
			unfed = append(unfed, fmt.Sprintf("%s.%s (%s)", nodeName, inp.Name, inp.Type))
		}
	}
	return unfed
}

// MergeLLMValues merges LLM-provided creative content into the skeleton plan.
// The skeleton's structural fields are authoritative; the LLM only adds/overrides
// values, descriptions, assertions, selection strategy refinements, and retry config.
func MergeLLMValues(skeleton, llmPlan *plan.Plan) {
	// Build index of LLM steps by node name.
	llmSteps := map[string]*plan.Step{}
	for i := range llmPlan.Execution.Steps {
		llmSteps[llmPlan.Execution.Steps[i].Node] = &llmPlan.Execution.Steps[i]
	}

	for i := range skeleton.Execution.Steps {
		skelStep := &skeleton.Execution.Steps[i]
		llmStep, ok := llmSteps[skelStep.Node]
		if !ok {
			continue
		}

		// Accept description from LLM.
		if llmStep.Description != "" {
			skelStep.Description = llmStep.Description
		}

		// Accept assertions from LLM.
		if llmStep.Assertions != nil {
			skelStep.Assertions = llmStep.Assertions
		}

		// Accept retry config from LLM.
		if llmStep.Retry != nil {
			skelStep.Retry = llmStep.Retry
		}

		// Merge values.
		if llmStep.Values == nil {
			continue
		}
		if skelStep.Values == nil {
			skelStep.Values = map[string]plan.StepValue{}
		}

		for inputName, llmVal := range llmStep.Values {
			skelVal, exists := skelStep.Values[inputName]

			if !exists {
				// Skeleton has no entry for this input. Accept literal from LLM
				// but strip any from/select (LLM shouldn't set structural fields).
				if llmVal.Default != nil {
					skelStep.Values[inputName] = plan.StepValue{
						Default: llmVal.Default,
					}
				}
				continue
			}

			// Skeleton has an entry. Merge based on what skeleton has.
			if skelVal.From != "" && skelVal.Select != nil {
				// Select edge: accept strategy/filter/sortField/index/prompt overrides.
				if llmVal.Select != nil {
					if llmVal.Select.Strategy != "" {
						skelVal.Select.Strategy = llmVal.Select.Strategy
					}
					if llmVal.Select.Filter != "" {
						skelVal.Select.Filter = llmVal.Select.Filter
					}
					if llmVal.Select.SortField != "" {
						skelVal.Select.SortField = llmVal.Select.SortField
					}
					if llmVal.Select.Index != 0 {
						skelVal.Select.Index = llmVal.Select.Index
					}
					if llmVal.Select.Prompt != "" {
						skelVal.Select.Prompt = llmVal.Select.Prompt
					}
				}
				skelStep.Values[inputName] = skelVal
			} else if skelVal.From != "" {
				// Scalar from ref: skeleton is authoritative, ignore LLM changes.
				// But if LLM tries to add Select to a scalar edge, ignore it.
			} else {
				// Graph default or empty: accept LLM literal override.
				if llmVal.Default != nil {
					skelVal.Default = llmVal.Default
				}
				skelStep.Values[inputName] = skelVal
			}
		}
	}
}

// setMetadataWithTime populates plan metadata with a specific time.
func setMetadataWithTime(p *plan.Plan, g *graph.Graph, ga *GoalAnalysis, prompt string, now time.Time) {
	p.Metadata.Prompt = prompt
	p.Metadata.GraphVersion = g.Version
	if p.Metadata.Created.IsZero() {
		p.Metadata.Created = now
	}
}

// lookupElementFieldPath finds the elementField name for an input fed by a
// select edge. It returns the elementField Name (not the gjson path) so that
// plans remain decoupled from response structure. The engine resolves the
// name to a gjson path at runtime via resolveElementFieldPath.
// Falls back to inputName if no matching elementField exists.
func lookupElementFieldPath(g *graph.Graph, sourceRef, inputName string) string {
	srcNode := splitNodeName(sourceRef)
	srcField := sourceRef[len(srcNode)+1:]
	node := g.Nodes[srcNode]
	if node == nil {
		return inputName
	}
	for _, out := range node.Outputs {
		if out.Name == srcField {
			for _, ef := range out.ElementFields {
				if ef.Name == inputName {
					return ef.Name
				}
			}
			break
		}
	}
	return inputName
}

// splitNodeName extracts the node name from a "node.field" reference.
func splitNodeName(ref string) string {
	parts := strings.SplitN(ref, ".", 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		key := s[i]
		j := i - 1
		for j >= 0 && s[j] > key {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = key
	}
}
