package archive

import "regexp"

// AutoGenPrefixRe matches auto-generated run/batch directory prefixes.
var AutoGenPrefixRe = regexp.MustCompile(`^(run|batch)-`)

// IsNamed returns true if the directory name represents a named/saved run or batch.
// A directory is named if it starts with "!" or doesn't match the auto-generated
// run-/batch- prefix pattern.
func IsNamed(dirName string) bool {
	if len(dirName) > 0 && dirName[0] == '!' {
		return true
	}
	return !AutoGenPrefixRe.MatchString(dirName)
}

// IsAutoGenerated returns true if the directory name matches the auto-generated
// run-/batch- prefix pattern (e.g. "run-20260101-120000-abcd1234").
func IsAutoGenerated(dirName string) bool {
	return AutoGenPrefixRe.MatchString(dirName)
}
